name: Build and Release Templ

on:
  push:
    tags:
      - 'v*'   # Triggers on git tag like v1.0.0

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Install
        run: cmake --install build --prefix dist

      - name: Package
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          PLATFORM=""
          EXT="tar.gz"
          
          # Handle each platform
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            PLATFORM="Windows"
            EXT="zip"
            mkdir -p dist/templ
            cp dist/bin/templ dist/templ/
            cp -r dist/share/templ dist/templ/templates
            zip -r Templ-${VERSION}-${PLATFORM}.${EXT} dist/templ
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            PLATFORM="MacOS"
            mkdir -p dist/templ
            cp dist/bin/templ dist/templ/
            cp -r dist/share/templ dist/templ/templates
            tar -czf Templ-${VERSION}-${PLATFORM}.${EXT} -C dist templ
          else
            PLATFORM="Linux"
            mkdir -p dist/templ
            cp dist/bin/templ dist/templ/
            cp -r dist/share/templ dist/templ/templates
            tar -czf Templ-${VERSION}-${PLATFORM}.${EXT} -C dist templ
          fi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: Templ-*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
